### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by f1fty28ty** [f1fty28ty/CSCI1300_Project3#1]
- [ ] Make a Boss. [Boss Class]
    Different attack DMG
    Health scales on dmg up to lvl 10
    Different attacks the player can roll for
    stab/slash/power attack/heal different percents for it

- [x] Have different enemies. [Enemy Class]
    Different attack DMG
    Different Health.
- [x] Make a profile / inventory [Player class]
    shows player health out of their max health
    shows level
    shows dmg
    shows def

- [ ] Make a shop [shop class]
    buy health potions
    buy gear
        sword/armor
    buy dungeon key
    print player name
    checks for the money to buy
    checks if the player already has this item
    depending what the player buys change the char

- [ ] Make a level class
has a nested class for the monsters of the area.
the puts a time spent in the area

- [ ] sort out all the time spent in the areas from most time to least time.
